[WIP] Iss hipcms 914
HiP-App/HiP-UserStore pull request #32
Opened 2018-01-13 17:25 UTC by Musaevt

Moving User Actions from Achievements service to UserStore. Now all User related Information will be stored in UserStore and all other services (e.g Achievement) have to query it to get or put info.

2018-01-19 10:21 UTC, SvenEV reviewed
Hey, since I'm now in Team Rabbit, I think it's better if Michél reviews this PR. From a first look, the resource type inheritance looks a bit different to how I thought it should look, but I guess @mb236 knows better whether this is as he intended it.

2018-02-18 18:44 UTC, mb236 requested changes
Looks good, just a few little things

2018-02-18 18:44 UTC, mb236 commented on HiP-UserStore/appsettings.json
> +    "ThumbnailUrlPattern": null
Since we are now using the DataStore SDK, there should also be an entry for the DataStoreHost with default value null (see Achievements).

2018-02-18 18:44 UTC, mb236 commented on HiP-UserStore/Controllers/ActionsController.cs
> +    [Authorize]
Indentation is wrong

2018-02-18 18:44 UTC, mb236 commented on HIP-UserStore.Model/ActionTypes.cs
> +        /// Initializes the fieldd
Typo

2018-02-19 10:18 UTC, mb236 approved these changes
Should be fine 👍

2018-02-19 11:13 UTC, merged